GITHUB_URL = "https://github.com/dimanu-py"
LINKEDIN_URL = "https://www.linkedin.com/in/diego-martinez-nu%C3%B1ez/"
PROJECT_URL = "https://github.com/dimanu-py/advent-py"
ORIGINAL_PROJECT_URL = "https://github.com/mouredev/adeviento-web/tree/main"
WEB_URL = "http://localhost:3000"